name: Build and Push Docker Image to docker registry and github registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_password }}

    - name: Get latest release tag
      id: get_latest_release
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        owner: PixelWelt
        repo: ThalamOS

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        file: dockerfile
        push: true
        tags: ${{ secrets.docker_username }}/thalamos:latest,${{ secrets.docker_username }}/thalamos:${{ steps.get_latest_release.outputs.release }}
    
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main
    
    - name: log in to Github Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    
    - name: 'Build Inventory Image'
      run: |
        docker build . --tag ghcr.io/pixelwelt/thalamos:latest --tag ghcr.io/pixelwelt/thalamos:${{ steps.get_latest_release.outputs.release }}
        docker push ghcr.io/pixelwelt/thalamos:latest
        docker push ghcr.io/pixelwelt/thalamos:${{ steps.get_latest_release.outputs.release }}
    