name: generate doxygen documentation
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Doxygen
              run: |
                   sudo apt install doxygen graphviz -y
                   git submodule add https://github.com/jothepro/doxygen-awesome-css.git

            - name: Generate Doxygen documentation
              run: |
                  ls -la
                  doxygen Doxyfile
            
            - name: Deploy Doxygen documentation
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.DOCS_TOKEN }}
                  publish_dir: ./docs/html