on:
    push:
      branches:
        - main

    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@v2

          - name: log in to Github Container Registry
            uses: docker/login-action@v2
            with:
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ secrets.GHCR_TOKEN }}

          - name: 'Build Inventory Image'
            run: |
              docker build . --tag ghcr.io/pixelwelt/thalamos:latest --tag ghcr.io/pixelwelt/thalamos:${{ steps.get_latest_release.outputs.release }}
              docker push ghcr.io/pixelwelt/thalamos:latest
              docker push ghcr.io/pixelwelt/thalamos:${{ steps.get_latest_release.outputs.release }}