on:
    push:
      branches:
        - main

jobs:
      build:
        runs-on: ubuntu-latest

        steps:
          - name: Get latest release tag
            id: get_latest_release
            uses: pozetroninc/github-action-get-latest-release@master
            with:
              owner: PixelWelt
              repo: ThalamOS
              
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@v2

          - name: log in to Github Container Registry
            uses: docker/login-action@v2
            with:
              registry: ghcr.io
              username: ${{github.repository_owner }}
              password: ${{secrets.GHCR_TOKEN }}

          - name: 'Build and push Docker image'
            run: |
              docker build . --tag ghcr.io/pixelwelt/thalamos:latest --tag ${{steps.get_latest_release.outputs.release}}
              docker push ghcr.io/pixelwelt/thalamos:latest
              docker push ghcr.io/pixelwelt/thalamos:${{steps.get_latest_release.outputs.release }}